services:
  exceltools.api:
    image: excel-tools-api
    container_name: ExcelTools.api
    build:
      context: .
      dockerfile: Services/ExcelTools.API/Dockerfile
    links:
      - exceltools.database
    env_file:
      - ./.env/api_dev.env
    ports:
      - "5033:8080"
    depends_on:
      - exceltools.database

  exceltools.database:
    image: postgres:latest
    container_name: ExcelTools.database
    env_file:
      - ./.env/db_dev.env
    volumes:
      - ./.containers/products-db:/var/lib/postgresql/data
    ports:
      - 5440:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 1m30s
      timeout: 60s
      retries: 5
      start_period: 80s
