# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI .NET

on:
  push:
    branches: [ "development","master" ]
  pull_request:
    branches: [ "development","master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src/Services/ExcelTools.API/ExcelTools.API.csproj
    - name: Build
      run: dotnet build --no-restore src/Services/ExcelTools.API/ExcelTools.API.csproj
    #- name: Test
    # run: dotnet test --no-build --verbosity normal
